namespace PleaseUndo
{
    public enum PUErrorCode
    {
        PU_OK = 0,
        PU_ERRORCODE_SUCCESS = 0,
        PU_ERRORCODE_GENERAL_FAILURE = -1,
        PU_ERRORCODE_INVALID_SESSION = 1,
        PU_ERRORCODE_INVALID_PLAYER_HANDLE = 2,
        PU_ERRORCODE_PLAYER_OUT_OF_RANGE = 3,
        PU_ERRORCODE_PREDICTION_THRESHOLD = 4,
        PU_ERRORCODE_UNSUPPORTED = 5,
        PU_ERRORCODE_NOT_SYNCHRONIZED = 6,
        PU_ERRORCODE_IN_ROLLBACK = 7,
        PU_ERRORCODE_INPUT_DROPPED = 8,
        PU_ERRORCODE_PLAYER_DISCONNECTED = 9,
        PU_ERRORCODE_TOO_MANY_SPECTATORS = 10,
        PU_ERRORCODE_INVALID_REQUEST = 11,
    }
}
