namespace PleaseUndo
{
    public enum GGPOErrorCode
    {
        GGPO_OK = 0,
        GGPO_ERRORCODE_SUCCESS = 0,
        GGPO_ERRORCODE_GENERAL_FAILURE = -1,
        GGPO_ERRORCODE_INVALID_SESSION = 1,
        GGPO_ERRORCODE_INVALID_PLAYER_HANDLE = 2,
        GGPO_ERRORCODE_PLAYER_OUT_OF_RANGE = 3,
        GGPO_ERRORCODE_PREDICTION_THRESHOLD = 4,
        GGPO_ERRORCODE_UNSUPPORTED = 5,
        GGPO_ERRORCODE_NOT_SYNCHRONIZED = 6,
        GGPO_ERRORCODE_IN_ROLLBACK = 7,
        GGPO_ERRORCODE_INPUT_DROPPED = 8,
        GGPO_ERRORCODE_PLAYER_DISCONNECTED = 9,
        GGPO_ERRORCODE_TOO_MANY_SPECTATORS = 10,
        GGPO_ERRORCODE_INVALID_REQUEST = 11,
    }
}
