name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore src/PleaseUndo.csproj
      - name: Restore dependencies (testing)
        run: dotnet restore tests/PleaseUndoTest/PleaseUndoTest.csproj
      - name: Build
        run: dotnet build src/PleaseUndo.csproj --no-restore
      - name: Testing
        run: dotnet test tests/PleaseUndoTest/PleaseUndoTest.csproj --no-restore
